EventWorlds: [ home, home_nether, home_the_end, mine, mine_nether, mine_the_end ]
PoleWorld: spawn
PoleCoords: [ 2100, 75, 943 ]
SkullFacings: [ WEST, NORTH, SOUTH, EAST ]
OriginalWinCommands:
- titles unlock %player% Maypole
AnyWinCommands:
- - give %player% diamond
  - give %player% emerald
- - money grant %player% 100
  - tell player Have some money.