main: com.winthier.maypole.MaypolePlugin

name: Maypole
version: 0.1

description: Maypole Event
author: StarTux
api-version: 1.18

depend: [Exploits, WorldMarker, Mytems]

commands:
  maypole:
    description: Admin interface
    permission: maypole.maypole
    usage: /maypole
  hi:
    description: Maypole highscore
    permission: maypole.hi
    usage: /hi

permissions:
  maypole.maypole:
    default: op
  maypole.hi:
    default: true