main: com.winthier.maypole.MaypolePlugin

name: Maypole
version: 0.1

description: Maypole Event
author: StarTux
api-version: 1.18

depend: [Core, SQL, PlayerCache, Exploits, Mytems, Sidebar, Fam]

commands:
  maypole:
    description: Player interface
    permission: maypole.maypole
    usage: /maypole

  maypoleadmin:
    aliases: [maypoleadm]
    description: Admin interface
    permission: maypole.admin
    usage: /maypoleadmin

permissions:
  maypole.maypole:
    description: Play maypole, use the /maypole command
    default: op

  maypole.admin:
    description: Use the /maypoleadmin command
    default: op
